on:
  - push

name: Build linux wheels

jobs:
  build:
    name: Build wheels
    runs-on: ubuntu-latest

    env:
      CIBW_ARCHS_LINUX: "auto aarch64"
      CIBW_BUILD: "cp36-* cp37-* cp38-* cp39-*"
      CIBW_BEFORE_BUILD_LINUX: "pip install cython && apt-get update -y && apt-get install -y libsystemd-dev"
      CIBW_MANYLINUX_X86_64_IMAGE: manylinux_2_24
      CIBW_MANYLINUX_I686_IMAGE: manylinux_2_24
      CIBW_MANYLINUX_AARCH64_IMAGE: manylinux_2_24
      CIBW_TEST_SKIP: "*"

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - uses: docker/setup-qemu-action@v1
        with:
          platforms: arm64

      - name: Install build dependencies
        run: python -m pip install cibuildwheel==1.11.1.post1

      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse

      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl
